INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3');
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx');
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2');