INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_USER','USER');
INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_ADMIN','ADMIN');


INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3','dffgdfgfgbfgbgbgbfgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx','dffgdfgfgbfttttgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2','dffgdfdddddgbgbfgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('admin@prova.com','Super','Admin','3454RgfgFGBNHJUY2','dffgdfdddddgffffb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_ADMIN'));
