
INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('USER','USER');

INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3','dffgdfgfgbfgbgbgbfgb454534',1,'{bcrypt}PASSWORD',(SELECT ID FROM RUOLO WHERE RUOLO = 'USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx','dffgdfgfgbfttttgb454534',1,'{bcrypt}PASSWORD',(SELECT ID FROM RUOLO WHERE RUOLO = 'USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2','dffgdfdddddgbgbfgb454534',1,'{bcrypt}PASSWORD',(SELECT ID FROM RUOLO WHERE RUOLO = 'USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova3@prova.com','Marco','Blu','3454RFDFGBNHJUY1','dff222fdddddgbgbfgb454534',1,'{bcrypt}$2a$12$Yd/IeEr1Z5ch1LxIoKW2qeJRmwn7FQWTADZZpLFQxw2XHTHmvhmCC',(SELECT ID FROM RUOLO WHERE RUOLO = 'USER'));