--PRODOTTO E STOCK

INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('12.4','COMPUTER','dgfgdfgdf45mnbv');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('222.32','CELLULARE','dgfgdfgdfaaa4345');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('10.3','CARICA BATTERIE','dgfgdwwdf454345');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('2.12','CARICA CELLULARE','rgvbdfgdf454345');

INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(12,(SELECT ID FROM PRODOTTO WHERE NOME = 'COMPUTER'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(3,(SELECT ID FROM PRODOTTO WHERE NOME = 'CELLULARE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(7,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA BATTERIE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(5,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA CELLULARE'));

--UTENTE
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3','dffgdfgfgbfgbgbgbfgb454534');
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx','dffgdfgfgbfttttgb454534');
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2','dffgdfdddddgbgbfgb454534');

--1

--ORDINE
INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE) VALUES('123A',(SELECT ID FROM UTENTE WHERE EMAIL = 'prova@prova.com'));

--MOVIMENTO
INSERT INTO MOVIMENTO(ID_ORDINE,ID_PRODOTTO,QUANTITA) VALUES((SELECT ID FROM ORDINE WHERE ORDINE_ID='123A'),(SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO = 'rgvbdfgdf454345'),3);

--2

--ORDINE
INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE) VALUES('564W',(SELECT ID FROM UTENTE WHERE EMAIL = 'prova1@prova.com'));

--MOVIMENTO
INSERT INTO MOVIMENTO(ID_ORDINE,ID_PRODOTTO,QUANTITA) VALUES((SELECT ID FROM ORDINE WHERE ORDINE_ID='564W'),(SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO = 'dgfgdfgdf45mnbv'),10);
INSERT INTO MOVIMENTO(ID_ORDINE,ID_PRODOTTO,QUANTITA) VALUES((SELECT ID FROM ORDINE WHERE ORDINE_ID='564W'),(SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO = 'dgfgdfgdfaaa4345'),2);
