INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_USER','USER');
INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_ADMIN','ADMIN');


-- PRODOTTO
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('12.4','COMPUTER','dgfgdfgdf45mnbv',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('222.32','CELLULARE','dgfgdfgdfaaa4345',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('10.3','CARICA BATTERIE','dgfgdwwdf454345',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('2.12','CARICA CELLULARE','rgvbdfgdf454345',1);

-- STOCK
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID,VERSION) VALUES(12,(SELECT ID FROM PRODOTTO WHERE NOME = 'COMPUTER'),0);
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID,VERSION) VALUES(3,(SELECT ID FROM PRODOTTO WHERE NOME = 'CELLULARE'),0);
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID,VERSION) VALUES(7,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA BATTERIE'),0);
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID,VERSION) VALUES(5,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA CELLULARE'),0);

-- UTENTE
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3','UTENTE_1',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx','UTENTE_2',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2','UTENTE_3',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('admin@prova.com','Super','Admin','3454RFfdfdHJUY2','UTENTE_4',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_ADMIN'));


--ORDINE

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-01',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T10:00:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-02',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T10:05:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-03',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T10:10:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-04',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T10:15:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-05',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T10:20:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-06',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T10:25:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-07',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T10:30:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-08',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T10:35:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-09',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T10:40:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-10',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T10:45:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-11',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T10:50:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-12',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T10:55:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-13',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T11:00:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-14',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T11:05:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-15',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T11:10:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-16',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T11:15:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-17',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T11:20:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-18',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T11:25:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-19',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T11:30:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-20',(SELECT ID FROM UTENTE WHERE EMAIL='prova1@prova.com'),'CREATO',1,'2026-02-01T11:35:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-21',(SELECT ID FROM UTENTE WHERE EMAIL='prova2@prova.com'),'CREATO',1,'2026-02-01T11:40:00','N');

INSERT INTO ORDINE(ORDINE_ID,ID_UTENTE,STATO,VERSION,TIMESTAMP_INS,FLG_ANNULLO)
VALUES('ORD-22',(SELECT ID FROM UTENTE WHERE EMAIL='prova@prova.com'),'CREATO',1,'2026-02-01T11:45:00','N');


INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-01'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-02'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-03'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-04'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        4, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-05'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-06'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-07'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-08'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        4, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-09'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-10'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-11'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-12'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        4, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-13'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-14'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-15'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-16'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        4, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-17'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-18'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-19'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-20'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        4, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-21'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-22'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='dgfgdfgdf45mnbv'),
        3, 0, 'N');


INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-02'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-04'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-06'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-08'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-10'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-12'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-14'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-16'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-18'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-20'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        2, 0, 'N');

INSERT INTO MOVIMENTO(ID_ORDINE, ID_PRODOTTO, QUANTITA, VERSION, FLG_ANNULLO)
VALUES ((SELECT ID FROM ORDINE WHERE ORDINE_ID='ORD-22'),
        (SELECT ID FROM PRODOTTO WHERE ID_PUBBLICO_PRODOTTO='rgvbdfgdf454345'),
        1, 0, 'N');
