INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('12.4','COMPUTER','dgfgdfgdf45mnbv',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('222.32','CELLULARE','dgfgdfgdfaaa4345',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('10.3','CARICA BATTERIE','dgfgdwwdf454345',1);
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION) VALUES('2.12','CARICA CELLULARE','rgvbdfgdf454345',1);

INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(12,(SELECT ID FROM PRODOTTO WHERE NOME = 'COMPUTER'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(3,(SELECT ID FROM PRODOTTO WHERE NOME = 'CELLULARE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(7,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA BATTERIE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(5,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA CELLULARE'));