INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION,FLG_ANNULLO) VALUES('12.4','COMPUTER','dgfgdfgdf45mnbv',1,'N');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION,FLG_ANNULLO) VALUES('222.32','CELLULARE','dgfgdfgdfaaa4345',1,'N');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION,FLG_ANNULLO) VALUES('10.3','CARICA BATTERIE','dgfgdwwdf454345',1,'N');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO,VERSION,FLG_ANNULLO) VALUES('2.12','CARICA CELLULARE','rgvbdfgdf454345',1,'N');

INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(12,(SELECT ID FROM PRODOTTO WHERE NOME = 'COMPUTER'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(3,(SELECT ID FROM PRODOTTO WHERE NOME = 'CELLULARE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(7,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA BATTERIE'));
INSERT INTO STOCK(QUANTITA,PRODOTTO_ID) VALUES(5,(SELECT ID FROM PRODOTTO WHERE NOME = 'CARICA CELLULARE'));


INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_USER','USER');
INSERT INTO RUOLO(RUOLO,RUOLO_ID) VALUES('ROLE_ADMIN','ADMIN');

--UTENTE
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova@prova.com','Paolo','Rossi','3454RFDFGBNHJUY3','dffgdfgfgbfgbgbgbfgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova1@prova.com','Luca','Verdi','3454RFDFGBNHJUYx','dffgdfgfgbfttttgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('prova2@prova.com','Marco','Bianchi','3454RFDFGBNHJUY2','dffgdfdddddgbgbfgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_USER'));
INSERT INTO UTENTE(EMAIL,NOME,COGNOME,CODICE_FISCALE,UTENTE_ID,VERSION,PASSWORD,ID_RUOLO) VALUES('admin@prova.com','Super','Admin','3454RFDFG222HJUY2','dffgdfdddfcvgbgbfgb454534',1,'{bcrypt}$2a$12$cAzMq542W0T5IUA3ebSeEuNkBL55qBGXZ41bBMSTUyMuwi9LkNX1i',(SELECT ID FROM RUOLO WHERE RUOLO = 'ROLE_ADMIN'));
