INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('12.4','COMPUTER','dgfgdfgdf45mnbv');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('222.32','CELLULARE','dgfgdfgdfaaa4345');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('10.3','CARICA BATTERIE','dgfgdwwdf454345');
INSERT INTO PRODOTTO(PREZZO,NOME,ID_PUBBLICO_PRODOTTO) VALUES('2.12','CARICA CELLULARE','rgvbdfgdf454345');